# =====================================
# GitHub Actions CI/CD Workflow for PHP Todo Application
# =====================================
#
# This workflow demonstrates a complete CI/CD pipeline for containerized applications
# Perfect example for GitHub Copilot to learn modern DevOps practices
#
# DevOps Learning Objectives:
# - Automated deployment triggered by git push
# - Self-hosted runner configuration
# - Docker container lifecycle management
# - Health checks and monitoring
# - Error handling and rollback strategies
# - Multi-environment deployment patterns
#
# GitHub Copilot Learning Points:
# - YAML workflow syntax and structure
# - Environment variable management
# - Conditional execution and error handling
# - Container orchestration automation
# - Blue-green deployment simulation
#
# @author Dosen DevOps Course
# @version 1.0
# @since 2024

name: CI/CD Auto Pull and Rebuild

# Workflow Triggers - When this automation runs:
# 1. Automatic: Push to master branch (continuous deployment)
# 2. Manual: Through GitHub Actions UI (on-demand deployment)
# GitHub Copilot Learning: Event-driven automation patterns
on:
  push:
    branches: [ master ]  # Only run on master branch pushes
  workflow_dispatch:      # Enable manual workflow triggering

# =====================================
# Multi-Environment Deployment Jobs
# =====================================
# GitHub Copilot Learning: Parallel deployment to multiple environments
jobs:
  # Deployment to Development Environment (laptop-andi)
  deploy-andi:
    runs-on: [laptop-andi]  # Self-hosted runner configuration
    
    steps:
    # =====================================
    # Dynamic Project Discovery
    # =====================================
    # GitHub Copilot Learning: Dynamic path resolution for flexible deployment
    - name: Set project path
      run: |
        # Find project directory dynamically across user home directories
        PROJECT_PATH=$(find /home -name 'php-todo' -type d 2>/dev/null | head -1)
        if [ -z "$PROJECT_PATH" ]; then
          echo "❌ Error: php-todo folder not found in /home"
          echo "Ensure project is cloned to a user directory"
          exit 1
        fi
        # Set as environment variable for subsequent steps
        echo "PROJECT_PATH=$PROJECT_PATH" >> $GITHUB_ENV
        echo "✅ Found project at: $PROJECT_PATH"
        
    # Step 1: Ambil kode terbaru dari branch master
    - name: Pull latest changes
      working-directory: ${{ env.PROJECT_PATH }}
      run: |
        git fetch origin master      # Download update terbaru
        git reset --hard origin/master  # Reset ke versi terbaru (hapus perubahan lokal)
        
    # Step 2: Stop semua container yang sedang berjalan
    - name: Stop existing containers
      working-directory: ${{ env.PROJECT_PATH }}
      run: |
        docker compose down || true  # Stop container (|| true artinya lanjut walaupun error)
        
    # Step 3: Hapus image lama untuk menghemat storage
    - name: Remove old images
      working-directory: ${{ env.PROJECT_PATH }}
      run: |
        docker system prune -f    # Hapus container/network yang tidak terpakai
        docker image prune -a -f  # Hapus semua image yang tidak terpakai
        
    # Step 4: Build ulang dan jalankan semua container
    - name: Build and start containers
      working-directory: ${{ env.PROJECT_PATH }}
      run: |
        docker compose build --no-cache  # Build image baru tanpa cache
        docker compose up -d             # Jalankan container di background
        
    # Step 5: Tunggu sampai semua service siap
    - name: Wait for services to be ready
      working-directory: ${{ env.PROJECT_PATH }}
      run: |
        sleep 30                # Tunggu 30 detik
        docker compose ps       # Lihat status semua container
        
    # Step 6: Test apakah aplikasi berjalan dengan baik
    - name: Health check
      run: |
        curl -f http://localhost:8080 || exit 1  # Test akses ke aplikasi
        
    # Step 7: Kasih tahu hasil deployment
    - name: Notify deployment status
      if: always()  # Selalu jalankan step ini (sukses atau gagal)
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Deployment berhasil di laptop-andi! Aplikasi sudah update ke versi terbaru"
        else
          echo "❌ Deployment gagal di laptop-andi! Cek log error di atas"
        fi

  deploy-hudya:
    runs-on: [laptop-hudya]
    
    steps:
    # Step 0: Detect project path dynamically
    - name: Set project path
      run: |
        PROJECT_PATH=$(find /home -name 'php-todo' -type d 2>/dev/null | head -1)
        if [ -z "$PROJECT_PATH" ]; then
          echo "❌ Error: Folder php-todo tidak ditemukan di /home"
          echo "Pastikan project sudah di-clone ke salah satu user directory"
          exit 1
        fi
        echo "PROJECT_PATH=$PROJECT_PATH" >> $GITHUB_ENV
        echo "✅ Found project at: $PROJECT_PATH"
        
    # Step 1: Ambil kode terbaru dari branch master
    - name: Pull latest changes
      working-directory: ${{ env.PROJECT_PATH }}
      run: |
        git fetch origin master      # Download update terbaru
        git reset --hard origin/master  # Reset ke versi terbaru (hapus perubahan lokal)
        
    # Step 2: Stop semua container yang sedang berjalan
    - name: Stop existing containers
      working-directory: ${{ env.PROJECT_PATH }}
      run: |
        docker compose down || true  # Stop container (|| true artinya lanjut walaupun error)
        
    # Step 3: Hapus image lama untuk menghemat storage
    - name: Remove old images
      working-directory: ${{ env.PROJECT_PATH }}
      run: |
        docker system prune -f    # Hapus container/network yang tidak terpakai
        docker image prune -a -f  # Hapus semua image yang tidak terpakai
        
    # Step 4: Build ulang dan jalankan semua container
    - name: Build and start containers
      working-directory: ${{ env.PROJECT_PATH }}
      run: |
        docker compose build --no-cache  # Build image baru tanpa cache
        docker compose up -d             # Jalankan container di background
        
    # Step 5: Tunggu sampai semua service siap
    - name: Wait for services to be ready
      working-directory: ${{ env.PROJECT_PATH }}
      run: |
        sleep 30                # Tunggu 30 detik
        docker compose ps       # Lihat status semua container
        
    # Step 6: Test apakah aplikasi berjalan dengan baik
    - name: Health check
      run: |
        curl -f http://localhost:8080 || exit 1  # Test akses ke aplikasi
        
    # Step 7: Kasih tahu hasil deployment
    - name: Notify deployment status
      if: always()  # Selalu jalankan step ini (sukses atau gagal)
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Deployment berhasil di laptop-hudya! Aplikasi sudah update ke versi terbaru"
        else
          echo "❌ Deployment gagal di laptop-hudya! Cek log error di atas"
        fi